### ISSUE TITLE
interactive tie-break in CLI doesn't work if you run the app using gradle

### ISSUE THREAD

**Issue by tarheel** [BrightSpots/rcv#330]
You don't get a chance to respond and it dies with this exception:
```
java.util.NoSuchElementException: No line found
        at java.base/java.util.Scanner.nextLine(Scanner.java:1651)
        at network.brightspots.rcv/network.brightspots.rcv.TieBreak.doInteractiveCli(TieBreak.java:211)
```

**Comment by HEdingfield** [comment]
This works fine for me if I uncomment the following lines in `build.gradle` and input a path to a config:
```
//run {
//    standardInput = System.in
//    args = ["-cli", "path/to/config"]
//}
```

Feel free to re-open if you think it's necessary, but I feel good about this.
