### ISSUE TITLE
CDF JSON generation leads to java memory error/tabulation failure

### ISSUE THREAD

**Issue by chughes297** [BrightSpots/rcv#550]
Rosemary was working with a Minneapolis ES&S CVR and tried to generate the CDF JSON, but her tabulation failed when the Tabulator attempted to generate the file. Here's the errors she got in the log: 

2021-03-10 10:04:31 EST INFO: Generating cast vote record CDF JSON file: C:\Users\Rosemary\Desktop\MN Demo\2021-03-10_10-04-
23_cvr_cdf.json...
java.lang.OutOfMemoryError: Java heap space
at javafx.graphics/com.sun.javafx.tk.quantum.QuantumToolkit.convertStops(Unknown Source)
at javafx.graphics/com.sun.javafx.tk.quantum.QuantumToolkit.createLinearGradientPaint(Unknown Source)
at javafx.graphics/com.sun.javafx.tk.Toolkit.getPaint(Unknown Source)
at javafx.graphics/com.sun.javafx.tk.Toolkit.getPaint(Unknown Source)
at javafx.graphics/javafx.scene.paint.LinearGradient.acc_getPlatformPaint(Unknown Source)
at javafx.graphics/javafx.scene.paint.Paint$1.getPlatformPaint(Unknown Source)
at javafx.graphics/com.sun.javafx.sg.prism.NGRegion.getPlatformPaint(Unknown Source)
at javafx.graphics/com.sun.javafx.sg.prism.NGRegion.renderBackgroundRectanglesDirectly(Unknown Source)
at javafx.graphics/com.sun.javafx.sg.prism.NGRegion.renderBackgroundRectangle(Unknown Source)
at javafx.graphics/com.sun.javafx.sg.prism.NGRegion.renderAsRectangle(Unknown Source)
at javafx.graphics/com.sun.javafx.sg.prism.NGRegion.renderContent(Unknown Source)
at javafx.graphics/com.sun.javafx.sg.prism.NGNode.doRender(Unknown Source)
at javafx.graphics/com.sun.javafx.sg.prism.NGNode.render(Unknown Source)
at javafx.graphics/com.sun.javafx.sg.prism.NGGroup.renderContent(Unknown Source)
at javafx.graphics/com.sun.javafx.sg.prism.NGRegion.renderContent(Unknown Source)
at javafx.graphics/com.sun.javafx.sg.prism.NGNode.doRender(Unknown Source)
at javafx.graphics/com.sun.javafx.sg.prism.NGNode.render(Unknown Source)
at javafx.graphics/com.sun.javafx.sg.prism.NGGroup.renderContent(Unknown Source)
at javafx.graphics/com.sun.javafx.sg.prism.NGRegion.renderContent(Unknown Source)
at javafx.graphics/com.sun.javafx.sg.prism.NGNode.doRender(Unknown Source)
at javafx.graphics/com.sun.javafx.sg.prism.NGNode.render(Unknown Source)
at javafx.graphics/com.sun.javafx.sg.prism.NGGroup.renderContent(Unknown Source)
at javafx.graphics/com.sun.javafx.sg.prism.NGRegion.renderContent(Unknown Source)
at javafx.graphics/com.sun.javafx.sg.prism.NGNode.doRender(Unknown Source)
at javafx.graphics/com.sun.javafx.sg.prism.NGNode.render(Unknown Source)
at javafx.graphics/com.sun.javafx.sg.prism.NGGroup.renderContent(Unknown Source)
at javafx.graphics/com.sun.javafx.sg.prism.NGRegion.renderContent(Unknown Source)
at javafx.graphics/com.sun.javafx.sg.prism.NGNode.doRender(Unknown Source)
at javafx.graphics/com.sun.javafx.sg.prism.NGNode.render(Unknown Source)
at javafx.graphics/com.sun.javafx.sg.prism.NGGroup.renderContent(Unknown Source)
at javafx.graphics/com.sun.javafx.sg.prism.NGRegion.renderContent(Unknown Source)
at javafx.graphics/com.sun.javafx.sg.prism.NGNode.doRender(Unknown Source)
2021-03-10 10:05:21 EST SEVERE: Error during tabulation:
java.lang.OutOfMemoryError: Java heap space
Tabulation failed!

**Comment by chughes297** [comment]
Doesn't seem like a priority. Not until the CDF gets more broad adoption, which will be a few years.
